/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kkp.swing;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author user
 */
public class PanelOpacity extends javax.swing.JPanel {

    /**
     * Creates new form PanelOpacity
     */
    public PanelOpacity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
protected void paintComponent(Graphics g) {
    // Mengatur transparansi panel
    Graphics2D g2 = (Graphics2D) g;
    AlphaComposite alphaComposite = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);
    g2.setComposite(alphaComposite);

    // Menjalankan kode asli untuk menggambar panel border
    GradientPaint gradientPaint = new GradientPaint(0, 0, Color.decode("#CB356B"), 0, getHeight(), Color.decode("#BD3F32"));
    g2.setPaint(gradientPaint);
    g2.fillRect(0, 0, getWidth() - 15, getHeight());
    g2.fillRoundRect(getWidth() - 20, 0, 20, getHeight(), 15, 15);

    // Mengembalikan komposit ke default
    g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 1.0f));

    super.paintComponent(g);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
