/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kkp.component;

import com.kkp.event.EventMenuSelected;
import com.kkp.form.Form_DataPengguna;
import com.kkp.model.Model_Menu;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JPanel {

    private EventMenuSelected event;
    
    public void addEventMenuSelected(EventMenuSelected eventMenuSelected){
        this.event = eventMenuSelected;
        listMenu1.addEventMenuSelected(eventMenuSelected);
    }
    
    public Menu() {
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();
    }
    
    private void init(){
        listMenu1.addItem(new Model_Menu("dashbrd", "Dashboard", Model_Menu.MenuType.MENU));
        
        
        listMenu1.addItem(new Model_Menu("", "________________________", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("", "Data Master", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("user_1", "Data Pengguna", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("class", "Data Kelas", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("teacher_1", "Data Guru", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("students", "Data Siswa", Model_Menu.MenuType.MENU));
        
        
        listMenu1.addItem(new Model_Menu("", "________________________", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("", "Data Transaksi", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("salary_teacher", "Data Gaji Guru", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("payment_student", "Data Pembayaran Siswa", Model_Menu.MenuType.MENU));
        
        
        listMenu1.addItem(new Model_Menu("", "________________________", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("", "Laporan", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("teacher_1", "Data Guru", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("students", "Data Siswa", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("salary_teacher", "Data Gaji Guru", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("payment_student", "Data Pembayaran Siswa", Model_Menu.MenuType.MENU));
        
        listMenu1.addItem(new Model_Menu("", "________________________", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("logout", "Log Out", Model_Menu.MenuType.MENU));
        

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu1 = new com.kkp.swing.ListMenu<>();

        panelMoving.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kkp/icon/bg_logo_rk_1.1.1.png"))); // NOI18N

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gradientPaint = new GradientPaint(0, 0, Color.decode("#CB356B"), 0, getHeight(), Color.decode("#BD3F32"));
        g2.setPaint(gradientPaint);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(g);
    }
    
    private int x;
    private int y;
    
    public void initMoving(JFrame frame){
        panelMoving.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent mouseEvent) {
                x = mouseEvent.getX();
                y = mouseEvent.getY();
            }
            
        });
        panelMoving.addMouseMotionListener(new MouseMotionAdapter(){
            @Override
            public void mouseDragged(MouseEvent MMouseEvent) {
                frame.setLocation(MMouseEvent.getXOnScreen() - x, MMouseEvent.getYOnScreen() - y);
            }
            
        });
        
      
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.kkp.swing.ListMenu<String> listMenu1;
    private javax.swing.JPanel panelMoving;
    // End of variables declaration//GEN-END:variables
}
